"""
Django settings for webFinPro project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
#from tkinter.tix import Tree
from django.core.handlers.wsgi import WSGIRequest
WSGIRequest.is_ajax = property(lambda self: self.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest')

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR='D:/charm/Django/webFinPro'
# BASE_DIR='/home/ubuntu/webpro/webFinPro'
# BASE_DIR='/home/ustc1/webpro/webFinPro'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read SECRET_KEY from environment variable in CI/production. Default is a
# placeholder to avoid committing the real secret into the repo.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'please-set-DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
ADMINS=[('lj-fin', 'lj340111@sina.com'),]

# Application definition

INSTALLED_APPS = [
    'pageIndex.apps.PageindexConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #'pageIndex',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    #'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webFinPro.urls'

DEFAULT_CHARSET='utf-8'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webFinPro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # }
    #  'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'findata',
    #     'USER': 'root',
    #     'PASSWORD': 'wshr340111',
    #     'HOST': 'nj-cdb-cvutu3ft.sql.tencentcdb.com',
    #     'PORT': '63869',
    # }
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'findata',
    #     'USER': 'root_user',
    #     'PASSWORD': 'wshr340111',
    #     'HOST': '222.195.89.229',
    #     'PORT': '3306',
    
    #   }
    'default': {
                    'ENGINE': 'django.db.backends.mysql',
                    'NAME': os.environ.get('DB_NAME', 'findata'),
                    'USER': os.environ.get('DB_USER', 'root_user'),
                    'PASSWORD': os.environ.get('DB_PASSWORD', ''),
                    'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
                    'PORT': os.environ.get('DB_PORT', '3306'),
                }
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'findata',
    #     'USER': 'root',
    #     'PASSWORD': 'wshr340111',
    #     'HOST': '10.206.16.6',
    #     'PORT': '3306',
    # }
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'findata',
    #     'USER': 'root',
    #     'PASSWORD': '12345678',
    #     'HOST': '127.0.0.1',
    #     'PORT': '3306',
    # }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

#TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True
# 设置session的存活周期，浏览器关闭即结束
# SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# SESSION_SAVE_EVERY_REQUEST = True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
#STATIC_URL = os.path.join(BASE_DIR, '/pageIndex/static/')
STATICFILES_DIRS = (
     
     os.path.join(BASE_DIR, 'static'),
 )

MEDIA_ROOT = os.path.join(BASE_DIR,'static')